export default {
  "login": "msingelwa",
  "id": 52956490,
  "node_id": "MDQ6VXNlcjUyOTU2NDkw",
  "avatar_url": "https://avatars0.githubusercontent.com/u/52956490?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/msingelwa",
  "html_url": "https://github.com/msingelwa",
  "followers_url": "https://api.github.com/users/msingelwa/followers",
  "following_url": "https://api.github.com/users/msingelwa/following{/other_user}",
  "gists_url": "https://api.github.com/users/msingelwa/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/msingelwa/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/msingelwa/subscriptions",
  "organizations_url": "https://api.github.com/users/msingelwa/orgs",
  "repos_url": "https://api.github.com/users/msingelwa/repos",
  "events_url": "https://api.github.com/users/msingelwa/events{/privacy}",
  "received_events_url": "https://api.github.com/users/msingelwa/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Lonwabo Msingelwa",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Bhuti Lloyd Upcoming Progammer",
  "twitter_username": 'LloydMsingelwa',
  "public_repos": 4,
  "public_gists": 0,
  "followers": 1,
  "following": 3,
  "created_at": "2019-07-16T09:09:38Z",
  "updated_at": "2020-11-04T11:57:57Z"
}